# s = set()
# n = input("Enter number:")
# s.add(int(n))
# n = input("Enter number:")
# s.add(int(n))
# n = input("Enter number:")
# s.add(int(n))
# n = input("Enter number:")
# s.add(int(n))
# n = input("Enter number:")
# s.add(int(n))
# n = input("Enter number:")
# s.add(int(n))
# n = input("Enter number:")
# s.add(int(n))
# n = input("Enter number:")
# s.add(int(n))

# print(s)

s = set()
s.add(18)
s.add('12')
print(s)